authorized_to_work_in_india: 'Yes'
government_employee: 'No'
military_service: 'No'
visa_sponsorship_required: 'No'
immediate_joiner: 'Yes'
relocate: 'Yes'
travel: 'Yes'
night_shift: 'Yes'
rotational_shift: 'Yes'
weekend_support: 'Yes'
contact_via_whatsapp: 'Yes'
contact_via_email: 'Yes'
contact_via_phone: 'Yes'
consent_apply_on_behalf: 'Yes'
consent_share_data_with_employers: 'Yes'
