authorized_to_work_in_india: '<Yes/No>'
government_employee: '<Yes/No>'
military_service: '<Yes/No>'
visa_sponsorship_required: '<Yes/No>'
immediate_joiner: '<Yes/No>'
relocate: '<Yes/No>'
travel: '<Yes/No>'
night_shift: '<Yes/No>'
rotational_shift: '<Yes/No>'
weekend_support: '<Yes/No>'
contact_via_whatsapp: '<Yes/No>'
contact_via_email: '<Yes/No>'
contact_via_phone: '<Yes/No>'
consent_apply_on_behalf: '<Yes/No>'
consent_share_data_with_employers: '<Yes/No>'
