linkedin:
  username: ''
  password: ''
naukri:
  username: ''
  password: ''
foundit:
  username: ''
  password: ''
cutshort:
  username: ''
  password: ''
indeed:
  username: ''
  password: ''
wellfound:
  username: ''
  password: ''
workday:
  username: ''
  password: ''
