version: '1.0'
personal:
  full_name: Althaf Hussain Syed
  gender: Male
  date_of_birth: '2001-06-03'
  nationality: Indian
  marital_status: Single
contact:
  email:
    primary: althafhussain.sd@gmail.com
    alternate: null
  phone:
    country: India
    country_code: '+91'
    number: '8184812249'
    full: +91 8184812249
  whatsapp:
    same_as_phone: true
    country: India
    country_code: '+91'
    number: '8184812249'
  alternate_phone: null
  preferred_contact:
  - Phone
  - WhatsApp
  - Email
  timezone: Asia/Kolkata
profiles:
  linkedin: https://www.linkedin.com/in/althafhussainsyed/
  github: https://github.com/ALTHAFHUSSAINSYED
  portfolio: https://althafportfolio.site/
career:
  designation: DevOps Engineer
  company: DXC Technology
  experience: 3y10m
  employment_status: Unemployed
  immediate_joiner: true
  last_working_day: '2026-06-29'
salary:
  current_ctc_lpa: 3.22
  expected_ctc_lpa: 10
